name : 'NASA Project CI'
on:
  push:
    branches : 'master'
  pull_request :
    branches : 'master'
jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run : npm install
    - run : npm run build --prefix client
