name: NASA Project CI 2
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build: 
    runs-on: [windows-latest]
    steps:
      - name: Checking Out
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build --prefix client
  #deploy:
    #needs: build 