name: NASA Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build: 
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checking Out
        users: actions/checkout@v2
      - name: Setup Node
        users: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build --prefix client
  #deploy:
    #needs: build 